---
title: "lab3"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<!--
```{r message=FALSE,warning=FALSE}
options(repos=c(CRAN="https://cran.cnr.berkeley.edu/"))
install.packages('mdsr')
library('mdsr')
```

install.packages('tinytex')
tinytext::install_tiny_tex()
library(tinytex)
-->
<!-- Make sure you have all package needed installed in your R, otherwise, you need to specify the repro and network to download the packages, it is a good habit to install the packages in R at the beginning.-->

```{r message=FALSE,warning=FALSE}
library(mdsr) 
library(tidyverse)
library(ggplot2)
library(tinytex)
```

```{r message=FALSE,warning=FALSE}
library(babynames)

BabynamesDist <- make_babynames_dist()
head(BabynamesDist,2)
```

```{r }
# help(package='babynames')
```


```{r}
ncol(BabynamesDist)
ncol(babynames)
```



```{r}
joseph <- BabynamesDist %>% filter(name == 'Joseph', sex == 'M')
```

```{r}
name_plot <- ggplot(data=joseph, aes(x=year))

name_plot <- name_plot + geom_bar(stat='identity', mapping=aes(y=count_thousands * alive_prob), fill='#b2d7e9', colour='white')

name_plot
name_plot <- name_plot + 
  geom_line(mapping=aes(x= year,y=count_thousands),size=2)

name_plot <- name_plot + 
  ylab('Number of People (thousands)') + xlab(NULL)

name_plot

```





```{r message=FALSE,warning=FALSE}
# install.packages('Hmisc')
library(Hmisc)
median_yob <-
  with(joseph, wtd.quantile(year, est_alive_today, probs = 0.5))
median_yob
```

```{r}
name_plot <- name_plot + 
  geom_bar(stat = 'identity', color = 'white', fill='#008fd5',
aes(y = ifelse(year==median_yob, est_alive_today/1000, 0)))

name_plot

```

```{r}
# ?Boston
mean(MASS::Boston$medv)
```
```{r}
Binary_medv <- ifelse(MASS::Boston$medv>25, 'rich','not so')
```


```{r}
name_plot +
  ggtitle("Age Distribution of American Boys Named Joseph") +
  geom_text(x = 1935, y = 40, label = "Number of Josephs\nborn each year") +
  geom_text(x = 1915, y = 13, label =
    "Number of Josephs\nborn each year\nestimated to be alive\non 1/1/2014",
    colour = "#b2d7e9")+ geom_text(x = 2003, y = 40,
    label = "The median\nliving Joseph\nis 37 years old",
            colour = "darkgray") +
  geom_curve(x = 1995, xend = 1974, y = 40, yend = 24,
    arrow = arrow(length = unit(0.3,"cm")), curvature = 0.5) + ylim(0, 42)
 
```
```{r}
Josephine <-filter(BabynamesDist, name =='Josephine' & sex =='F')
name_plot %+% Josephine
```

```{r}
many_names_plot <- name_plot + facet_grid(name ~ sex)
mnp <- many_names_plot %+% filter(BabynamesDist, name %in% c('Jessie','Marion','Jackie'))
mnp
```


```{r message=FALSE,warning=FALSE}
library(mosaic)
head(Galton)
```
```{r}
Galton_plot <- ggplot(data = Galton,mapping=aes(x=father, y=height))
Galton_plot <- Galton_plot + geom_point()
Galton_plot <- Galton_plot + facet_grid(.~ sex)
Galton_plot
```

```{r}
Galton_plot + geom_smooth(method='lm')
```


```{r}
library(mdsr)
head(MLB_teams, 2)
```


```{r message=FALSE}
names(MLB_teams)
# ?MLB_teams

plot_1 <- ggplot(data= MLB_teams,mapping=aes(x =yearID))
plot_1 + geom_bar(aes(fill=lgID)) 
  

plot_2 <- ggplot(data=MLB_teams, mapping=aes(x = payroll, y = attendance))
plot_2 + geom_point( aes(color=teamID, shape=factor(yearID))) + geom_smooth(aes(color=lgID)) 


  
```





```{r}
MLB_plot <- ggplot(data=MLB_teams,mapping=aes(x=WPct, y= payroll))
MLB_plot + geom_point() + 
  xlab("WPct") + ylab("payroll") + 
  geom_smooth(color='blue')

```


